### ISSUE TITLE
fail to build on node v0.10.22

### ISSUE THREAD

**Issue by fruch** [allenluce/node-autovivify#3]
```
../autovivify.cc: In static member function ‘static Nan::NAN_PROPERTY_GETTER_RETURN_TYPE AutoVivify::PropGetter(v8::Local<v8::String>, Nan::NAN_PROPERTY_GETTER_ARGS_TYPE)’:
../autovivify.cc:84:17: error: ‘class v8::String’ has no member named ‘IsSymbol’
make: *** [Release/obj.target/autovivify/autovivify.o] Error 1
```

I know it's old version, but just FYI

**Comment by allenluce** [comment]
Thanks for reporting this. Looks like a little work will be needed to work with 0.10.

**Comment by allenluce** [comment]
@fruch can you try the latest release?

**Comment by fruch** [comment]
I will take it for a spin...

**Comment by allenluce** [comment]
Thanks, please let me know how it goes for you!

**Comment by fruch** [comment]
It build fine for me on linux,
but on windows it's failing for a weird reason
```

C:\Users\ifruchte\Projects\megatron\node_modules\autovivify>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppBuild.targets(297,5): warning MSB8003: Could not find WindowsSDKDir variable from the registry.  TargetFrameworkVersion or PlatformToolset may be set to an invalid version number. [C:\Users\ifruchte\Projects\megatron\node_modules\autovivify\build\autovivify.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Platforms\x64\Microsoft.Cpp.x64.Targets(152,5): error MSB6006: "CL.exe" exited with code -1073741515. [C:\Users\ifruchte\Projects\megatron\node_modules\autovivify\build\autovivify.vcxproj]
gypnpm ERR! autovivify@1.0.7 install: `node-gyp rebuild`

```
other node-gyp modules are compiling just fine...

**Comment by allenluce** [comment]
@fruch I'm not sure why that's happening, but I've redone the package to be a binary release. Please have another go at installing the latest version (1.0.11) and let me know how it went.

**Comment by bchr02** [comment]
> but on windows it's failing for a weird reason

@fruch That error message in your last post can likely be fixed by:
1. using [windows-build-tools](https://github.com/felixrieseberg/windows-build-tools)
2. npm install autovivify --msvs_version=2015

**Comment by allenluce** [comment]
@fruch Are you still having the problem?

**Comment by fruch** [comment]
I've moved to node 4.6 since then, so I don't have 0.10 installed anymore, so from my POV this can be closed

**Comment by allenluce** [comment]
@fruch cool, thanks for following up.
